---
name: reviewdog
on: # yamllint disable-line rule:truthy
  push:

jobs:
  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: yamllint
        uses: reviewdog/action-yamllint@v1.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  markdownlint:
    name: runner / markdownlint ${{ matrix.pattern }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Make sure we lint all markdown files including in hidden directories
        pattern: ["**/*.md", ".**/*.md"]
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint ${{ matrix.pattern }}
        uses: reviewdog/action-markdownlint@v0.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          markdownlint_flags: ${{ matrix.pattern }}
          reviewdog_flags: -name=markdownlint:${{ matrix.pattern }}

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.5
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"

  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.26.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  misspell:
    name: runner / misspell
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@v1.7
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check

  languagetool:
    name: runner / languagetool
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-languagetool@v1.5
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          patterns: |
            **/*.md
            **/*.spec
            **/*.txt
          language: en
          disabled_rules: "DOUBLE_PUNCTUATION,WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,CURRENCY,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END,METRIC_UNITS_EN_US,ENGLISH_WORD_REPEAT_BEGINNING_RULE,GITHUB" # yamllint disable-line

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v1.19
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "-c .golangci.yml"
          level: "error"
          reporter: github-check
